# Répertoire où sont enregistrés les fichiers des référentiels après traitement
outputDir: output
# Répertoire où sont stockés les fichiers temporaires de travail du script
workDir: work
# Nom du fichier de log qui sera créé dans $workDir
logFile: isidore-referentiels.log

# delete-uris-query: sparql/delete-uris/delete-uris.rq

# Si ce paramètre est à True, le script va extraire les triplets d'alignement wikidata de chaque référentiel
# Le résultat de l'extraction est dans le répertoire $workDir/{id_du_referentiel}/wikidata/{id_du_referentiel}.ttl
# Cette extraction est réalisée à partir de la requête SPARQL 
wikidata: True

# A transformer en:
# wikidataAlignementQuery: sparql/wikidata/wikidata.rq
# Si ce paramètre n'est pas présent dans le fichier de config ou n'a aucune valeur, ne pas faire le traitement d'extraction des alignements wikidata


vocabularies:
  
  # ID du référentiel
  - id: rameau
    # Pour information seulement : lien vers la page de téléchargement des fichiers
    # Ce paramètre n'est pas utilisé par le script
    downloadPage: 
      - https://pef.bnf.fr/link/539d6d59-c2e3-4e17-b24c-d8a83ca11944#
    # Chemin vers le répertoire contenant les fichiers de données RDF du référentiel
    data: 
      - data/rameau
    # Liste de chemin vers des fichiers contenant chacun une requête SPARQL de mise à jour qui sera appliquée sur les données
    # A chaque exécution de requête SPARQL, le résultat est écrit dans un fichier $workDir/{id_du_referentiel}/tmp/{id_du_referentiel}.ttl
    sparql:
      - sparql/rameau/keep-only_isPartOf.ru
      - sparql/rameau/clean-domaines.ru
      - sparql/rameau/clean-aligned-with-geonames.ru
      - sparql/rameau/clean-combined-concepts.ru
      - sparql/rameau/clean-dict-concepts.ru
    # Liste des URIs unitaires à supprimer du dataset. Quand une URI est supprimée:
    #   - Tous les triplets dont elle est sujet ou objet sont supprimés
    #   - Les enfants (skos:narrower ou ^skos:broader) sont rattachés à ses parents
    delete-uris:
      - https://data.bnf.fr/concept/123456
      - https://data.bnf.fr/concept/456789
    # 1. Lit les alignements Wikidata de ce référentiel (rameau)
    # 2. Lit tous les alignements Wikidata des référentiels indiqués en paramètre
    # 3. Compare les alignements Wikidata de ce reférentiel avec tous les autres et trouve les concepts alignés sur les même URI Wikidata
    # 4. Génère un fichier CSV dans 
    wikidata-oper:
      - lcsh


  - id: lcsh
    downloadPage: 
      - https://id.loc.gov/download/     
    data: 
      - data/lcsh
    sparql:
      - sparql/lcsh/clean-combined-concepts.ru
    delete-uris: []
    wikidata-oper: []


  - id: bne
    downloadPage:
      - https://www.bne.es/es/iniciativas-proyectos/datos-enlazados-bne
    data:
      - data/bne
    sparql:
      - sparql/bne/clean-combined-concepts.ru
    delete-uris: []
    wikidata-oper:
      - lcsh
      - rameau

  - id: pactols
    downloadPage:
      - https://github.com/frantiq/PACTOLS
      - https://github.com/frantiq/PACTOLS/tree/master/pactols-latest-version/pactols_sujets_al
    data:
      - data/pactols
    sparql:
      - sparql/pactols/clean-anthroponymes-and-oeuvres.ru
    delete-uris: []
    wikidata-oper:
      - lcsh
      - rameau
      - bne