id: rameau
downloadPage:
  - https://pef.bnf.fr/link/539d6d59-c2e3-4e17-b24c-d8a83ca11944#
# Répertoire où sont enregistrés les fichiers des référentiels après traitement
outputDir: output
# Répertoire où sont stockés les fichiers temporaires de travail du script
workDir: work
# Nom du fichier de log qui sera créé dans $workDir
logFile: isidore-referentiels_rameau.log
clean:
  data: 
    - data/rameau
  sparql:
    - config/rameau/sparql/keep-only_isPartOf.ru
    - config/rameau/sparql/clean-domaines.ru
    - config/rameau/sparql/clean-aligned-with-geonames.ru
    - config/rameau/sparql/clean-combined-concepts.ru
    - config/rameau/sparql/clean-dict-concepts.ru
    - config/rameau/sparql/update-uri-wikidata.ru
  # Répertore pour stoker le résultat
  output: 
    - output_clean
report:
  # Répertoire où se trouve le fichier après de l'etape de nettoyage .
  data: 
    - output/rameau/output_clean
  # Répertore pour stoker le résultat
  output: 
    - output_report
  # Concepts
  algorithms:
    - libelles
    - alignement
    - statistique
integrate:
  report: 
    - output/rameau/output_report
  data: 
    - output/rameau/output_clean
  # Répertore pour stoker le résultat
  output: 
    - output_integrate
merge: []