id: rameau
downloadPage:
  - https://pef.bnf.fr/link/539d6d59-c2e3-4e17-b24c-d8a83ca11944#
data: 
  - data/rameau
# Répertoire où sont enregistrés les fichiers des référentiels après traitement
outputDir: output
# Répertoire où sont stockés les fichiers temporaires de travail du script
workDir: work
# Nom du fichier de log qui sera créé dans $workDir
logFile: isidore-referentiels_rameau.log
clean:
  sparql:
    - config/rameau/sparql/keep-only_isPartOf.ru
    - config/rameau/sparql/clean-domaines.ru
    - config/rameau/sparql/clean-aligned-with-geonames.ru
    - config/rameau/sparql/clean-combined-concepts.ru
    - config/rameau/sparql/clean-dict-concepts.ru
  output: work/rameau/output_clean
report:
  # Répertoire où se trouve le fichier après de l'etape de nettoyage .
  data: output_clean
  # Concepts
  algorithms:
    - labels
    - wikidata
    - statistique
Filter: []
merge: []