id: bne
downloadPage:
  - https://github.com/frantiq/PACTOLS
  - https://github.com/frantiq/PACTOLS/tree/master/pactols-latest-version/pactols_sujets_al
# Répertoire où sont stockés les fichiers temporaires de travail du script
workDir: work
# Nom du fichier de log qui sera créé dans $workDir
logFile: isidore-referentiels_bne.log
clean:
  data: 
    - data/bne
  sparql:
    - config/4-bne/sparql/clean-combined-concepts.ru
  # Répertore pour stoker le résultat
  output:
    - output/bne/output_clean
report:
  # Répertoire où se trouve le fichier après de l'etape de nettoyage .
  data: 
    - output/bne/output_clean
  # Répertore pour stoker le résultat
  output: 
    - output/bne/output_report
  # Concepts
  algorithms:
    - alignement
    - libelles
    - statistique
integrate:
  report: 
    - output/bne/output_report
  data: 
    - output/bne/output_clean
  # Répertore pour stoker le résultat
  output: 
    - output/bne/output_integrate