id: gemet
downloadPage: []
  #- https://www.archires.archi.fr/
  #- https://www.archires.archi.fr/
# Répertoire où sont enregistrés les fichiers des référentiels après traitement
outputDir: output
# Répertoire où sont stockés les fichiers temporaires de travail du script
workDir: work
# Nom du fichier de log qui sera créé dans $workDir
logFile: isidore-referentiels_gemet.log
clean:
  data: 
    - data/gemet
  sparql: []
  # Répertore pour stoker le résultat
  output:
    - output/gemet/output_clean
report:
  # Répertoire où se trouve le fichier après de l'etape de nettoyage .
  data: 
    - output/gemet/output_clean
  # Répertore pour stoker le résultat
  output: 
    - output/gemet/output_report
  # Concepts
  algorithms:
    - alignement
    - libelles
    - statistique
integrate:
  report: 
    - output/gemet/output_report
  data: 
    - output/gemet/output_clean
  # Répertore pour stoker le résultat
  output: 
    - output/gemet/output_integrate