PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?uriRef ?prefLabel_fr ?prefLabel_en ?prefLabel_es (GROUP_CONCAT(CONCAT(?label,"@",LANG(?label)); separator=", ") AS ?altLabel) (GROUP_CONCAT(CONCAT(?def,"@",LANG(?def)); separator=", ") AS ?definition) (GROUP_CONCAT(CONCAT(?parent_label,"@",LANG(?parent_label)); separator=", ") AS ?ParentLabel)
where {
    ?uriRef a skos:Concept .
    optional {
        ?uriRef skos:prefLabel ?prefLabel_fr .
        FILTER (LANG(?prefLabel_fr)="fr")        
    }
    optional {
        ?uriRef skos:prefLabel ?prefLabel_en .
        FILTER (LANG(?prefLabel_en)="en")        
    }
    optional {
        ?uriRef skos:prefLabel ?prefLabel_es .
        FILTER (LANG(?prefLabel_es)="es")        
    }
    optional {
        ?uriRef skos:altLabel ?label .       
    }
    optional {
        ?uriRef skos:definition ?def .
    }   
    optional {
       ?uriRef skos:broader ?parent .
       ?parent skos:prefLabel ?parent_label .
       FILTER(LANG(?parent_label) ="fr")
    }
}
Group by ?uriRef ?prefLabel_fr ?prefLabel_en ?prefLabel_es
Order by ?uriRef