id: archires
downloadPage:
  - https://www.archires.archi.fr/
  - https://www.archires.archi.fr/
# Répertoire où sont stockés les fichiers temporaires de travail du script
workDir: work
# Nom du fichier de log qui sera créé dans $workDir
logFile: isidore-referentiels_archires.log
clean:
  data: 
    - data/archires
  sparql: []
  # Répertore pour stoker le résultat
  output:
    - output/archires/output_clean
report:
  # Répertoire où se trouve le fichier après de l'etape de nettoyage .
  data: 
    - output/archires/output_clean
  dataStatistique:
    - data/statistics
  # Répertore pour stoker le résultat
  output: 
    - output/archires/output_report
  # Concepts
  algorithms:
    - alignement
    - libelles
    - statistique
integrate:
  report: 
    - output/archires/output_report
  data: 
    - output/archires/output_clean
  # Répertore pour stoker le résultat
  output: 
    - output/archires/output_integrate