id: pactols
downloadPage:
  - https://github.com/frantiq/PACTOLS
  - https://github.com/frantiq/PACTOLS/tree/master/pactols-latest-version/pactols_sujets_al
data: 
  - data/rameau
algorithms:
  - C:\Users\thoma\Documents\GitHub\isidore-referentiels\sparql\wikidata\wikidata_alignement.rq
  - label_exact
  - xxxxx
sparql:
  - sparql/rameau/keep-only_isPartOf.ru
  - sparql/rameau/clean-domaines.ru
Analyze:
  - sparql/analyze/analyze_referentiel.rq
Wikidata:
  - sparql/wikidata/wikidata.rq