id: lcsh
downloadPage: 
  - https://id.loc.gov/download/     
# Répertoire où sont stockés les fichiers temporaires de travail du script
workDir: work
# Nom du fichier de log qui sera créé dans $workDir
logFile: isidore-referentiels_lcsh.log
# Etapes
clean:
  data: 
    - data/lcsh
  sparql:
    - config/2-lcsh/sparql/clean-combined-concepts.ru
    - config/2-lcsh/sparql/clean-anonymous-concepts.ru
    - config/2-lcsh/sparql/clean-notes-concepts.ru
  output: 
    - output/lcsh/output_clean  
report:
  data: 
    - output/lcsh/output_clean
  dataStatistique:
    - data/statistics
  output: 
    - output/lcsh/output_report
  algorithms:
    - alignement
    - libelles
    - statistique
integrate:
  report: 
    - output/lcsh/output_report
  data: 
    - output/lcsh/output_clean
  output: 
    - output/lcsh/output_integrate