id: lcsh
downloadPage: 
  - https://id.loc.gov/download/     
data: 
  - data/lcsh
# Répertoire où sont enregistrés les fichiers des référentiels après traitement
OutputDir: Output
# Répertoire où sont stockés les fichiers temporaires de travail du script
WorkDir: Work
# Nom du fichier de log qui sera créé dans $workDir
logFile: isidore-referentiels_lcsh.log
# Etapes
clean:
  sparql:
    - config/lcsh/sparql/clean-combined-concepts.ru
    - config/lcsh/sparql/clean-anonymous-concepts.ru
report:
  - algorithms:
    - wikidata
    - E
    - N
integrate: []
merge: []