id: lcsh
downloadPage: 
  - https://id.loc.gov/download/     
data: 
  - data/lcsh
# Répertoire où sont enregistrés les fichiers des référentiels après traitement
outputDir: output
# Répertoire où sont stockés les fichiers temporaires de travail du script
workDir: work
# Nom du fichier de log qui sera créé dans $workDir
logFile: isidore-referentiels_lcsh.log
# Etapes
clean:
  sparql:
    - config/lcsh/sparql/clean-combined-concepts.ru
    - config/lcsh/sparql/clean-anonymous-concepts.ru
  output: work/lcsh/output_clean  
report:
  data: 
    - work/lcsh/output_clean
  output: 
    - work/lcsh/output_report
  algorithms:
    - alignement
    - labels
integrate: []
merge: []