PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
DELETE {
    ?s ?p ?o .
    ?otherSubject ?otherPredicate ?s .
} 
INSERT {
    # raccrocher les enfants au parent
    ?children skos:broader ?parent .
    ?parent skos:narrower ?children .
} 
WHERE 
{
    # supprimer tous les triplets dont l'URI est sujet
    ?s ?p ?o
    VALUES ?s {<"""+sURI+"""> }
        OPTIONAL { ?s skos:narrower|^skos:broader ?children . }
        OPTIONAL { ?s skos:broader|^skos:narrower ?parent . }
        # supprimer tous les triplets dont l'URI est objet
        OPTIONAL { ?otherSubject ?otherPredicate ?s }
}