id: geonames
downloadPage: 
  - https://www.geonames.org/ 
data: 
  - data/geonames
# Répertoire où sont enregistrés les fichiers des référentiels après traitement
outputDir: output
# Répertoire où sont stockés les fichiers temporaires de travail du script
workDir: work
# Nom du fichier de log qui sera créé dans $workDir
logFile: isidore-referentiels_geonames.log
# Etapes
clean:
  sparql:
    - config/geonames/sparql/insert_wikidata.ru
    - config/geonames/sparql/insert_skos.ru
  output: work/geonames/output_clean
report:
  data: 
    - work/geonames/output_clean
  output: 
    - work/geonames/output_report
  algorithms:
    - alignement
    - libelles
integrate:
  report: 
    - work/geonames/output_report
  resource: 
    - work/geonames/output_clean
  output: 
    - work/geonames/output_integrate
merge: []