id: geonames
downloadPage: 
  - https://www.geonames.org/ 
# Répertoire où sont enregistrés les fichiers des référentiels après traitement
outputDir: output
# Répertoire où sont stockés les fichiers temporaires de travail du script
workDir: work
# Nom du fichier de log qui sera créé dans $workDir
logFile: isidore-referentiels_geonames.log
# Etapes
clean:
  data: 
    - data/geonames
  sparql: 
    - config/geonames/sparql/insert_wikidata.ru
    - config/geonames/sparql/insert_skos.ru
  # Répertore pour stoker le résultat
  output: 
    - output/geonames/output_clean
report:
  data: 
    - output/geonames/output_clean
  # Répertore pour stoker le résultat
  output: 
    - output/geonames/output_report
  algorithms:
    - alignement
    - libelles
integrate:
  report: 
    - output/geonames/output_report
  data: 
    - output/geonames/output_clean
  # Répertore pour stoker le résultat
  output: 
    - output/geonames/output_integrate