id: bne
downloadPage:
  - https://github.com/frantiq/PACTOLS
  - https://github.com/frantiq/PACTOLS/tree/master/pactols-latest-version/pactols_sujets_al
data: 
  - data/bne
# Répertoire où sont enregistrés les fichiers des référentiels après traitement
outputDir: output
# Répertoire où sont stockés les fichiers temporaires de travail du script
workDir: work
# Nom du fichier de log qui sera créé dans $workDir
logFile: isidore-referentiels_bne.log
clean:
  sparql:
    - config/bne/sparql/clean-combined-concepts.ru
  output: work/bne/output_clean
report:
  # Répertoire où se trouve le fichier après de l'etape de nettoyage .
  data: 
    - work/bne/output_clean
  output: 
    - work/bne/output_report
  # Concepts
  algorithms:
    - labels
    - wikidata
    - statistique
Filter: []
merge: []