id: bne
downloadPage:
  - https://github.com/frantiq/PACTOLS
  - https://github.com/frantiq/PACTOLS/tree/master/pactols-latest-version/pactols_sujets_al
data: 
  - data/bne
# Répertoire où sont enregistrés les fichiers des référentiels après traitement
OutputDir: Output
# Répertoire où sont stockés les fichiers temporaires de travail du script
WorkDir: Work
# Nom du fichier de log qui sera créé dans $workDir
logFile: isidore-referentiels_bne.log
clean:
  sparql:
    - config/bne/sparql/clean-combined-concepts.ru
report:
  # Répertoire où se trouve le fichier après de l'etape de nettoyage .
  data: output_clean
  # Concepts
  algorithms:
    - Libelles_Labels
    - Wikidata
    - Statistique
Filter: []
merge: []